apiVersion: v1
kind: Endpoints
metadata:
  name: lizardo-metrics
  namespace: monitoring
  labels:
    k8s-app: lizardo
subsets:
  - addresses:
      - ip: 192.168.1.104
    ports:
      - name: metrics
        port: 8000
        protocol: TCP
