apiVersion: v1
kind: Endpoints
metadata:
    name: lizard-metrics
    labels:
        prometheus: k8s
subsets:
    - addresses:
    - ip: http://192.168.1.104/
ports:
    - name: metrics
      port: 8000
      protocol: TCP
